name: 'Compare Dependencies'
description: 'A GitHub Action for Node.js projects that automatically detects similar dependencies in pull requests, streamlining dependency management and preventing redundancy.'
inputs:
  openai_key:
    description: 'openai api key'
    required: true
  origin_branch:
    description: 'The branch to be used as the base for comparison, typically the main branch of the project. Can be customized if needed.'
  target_branch:
    description: 'The branch associated with the pull request, which contains the changes to be compared against the origin branch. Can be customized if needed.'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Compare
      id: compare
      shell: bash
      run: node dist/index.js
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ steps.compare.outputs.RESULTS }}
